# mcp-spec-v1.yaml
openapi: 3.0.3
info:
  title: "MCP (Model Context Protocol) - v1.0"
  description: |
    A standardized, streaming interface for Large Language Model (LLM) applications.
    This specification defines a set of endpoints that an MCP server, such as CogniScaffold,
    should implement to allow clients to interact with it in a consistent, streaming manner.
    All streaming responses use the Server-Sent Events (SSE) protocol.
  version: "1.0.0"

servers:
  - url: "http://127.0.0.1:5000"
    description: "Local development server for CogniScaffold (Reference Implementation)"

paths:
  /search:
    get:
      summary: "Search for Frameworks"
      description: |
        Searches the knowledge base for frameworks matching a keyword.
        Returns a stream of Server-Sent Events (SSE), with each event's `data` field
        containing a JSON object for a single `Framework` or a final `Done` event.
      operationId: "searchFrameworks"
      parameters:
        - name: q
          in: query
          required: true
          description: "The keyword to search for."
          schema:
            type: string
      responses:
        '200':
          description: "A stream of frameworks."
          content:
            text/event-stream:
              schema:
                type: string
                example: |
                  data: {"name": "SWOT Analysis", "description": "A strategic planning technique..."}

                  data: {"event": "done"}
  
  /template/{framework_name}:
    get:
      summary: "Get Framework Template"
      description: |
        Retrieves the Markdown template for a specific framework.
        Returns a stream of Server-Sent Events (SSE) containing a single `Template` object
        or an `Error` object, followed by a `Done` event.
      operationId: "getFrameworkTemplate"
      parameters:
        - name: framework_name
          in: path
          required: true
          description: "The name or alias of the framework (e.g., 'swot')."
          schema:
            type: string
      responses:
        '200':
          description: "A stream containing the framework template."
          content:
            text/event-stream:
              schema:
                type: string
                example: |
                  data: {"name": "SWOT Analysis", "template": "### SWOT Analysis..."}
                  
                  data: {"event": "done"}

  /suggest:
    post:
      summary: "Suggest Frameworks"
      description: |
        Suggests relevant frameworks based on a problem description provided in the request body.
        Returns a stream of Server-Sent Events (SSE), with each event's `data` field
        containing a JSON object for a single `Suggestion` or a final `Done` event.
      operationId: "suggestFrameworks"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                problem:
                  type: string
                  description: "A detailed description of the problem to analyze."
                  example: "We need to analyze our market position."
      responses:
        '200':
          description: "A stream of framework suggestions."
          content:
            text/event-stream:
              schema:
                type: string
                example: |
                  data: {"name": "SWOT Analysis", "use_case": "Quickly assessing a situation...", "score": 4}

                  data: {"event": "done"}

components:
  schemas:
    Framework:
      type: object
      properties:
        name:
          type: string
          description: "The full name of the framework."
        description:
          type: string
          description: "A brief description of the framework."
    Template:
      type: object
      properties:
        name:
          type: string
          description: "The name of the framework for which the template is provided."
        template:
          type: string
          description: "The Markdown-formatted template string."
    Suggestion:
      type: object
      properties:
        name:
          type: string
          description: "The name of the suggested framework."
        use_case:
          type: string
          description: "The primary use case for this framework."
        score:
          type: integer
          description: "A relevance score calculated by the server."
    Error:
      type: object
      properties:
        error:
          type: string
          description: "An error message."
    Done:
      type: object
      properties:
        event:
          type: string
          enum: [done]
